// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PendingDocuments pending documents
//
// swagger:model PendingDocuments
type PendingDocuments struct {

	// id
	// Required: true
	ID *int32 `json:"id"`

	// title
	// Required: true
	Title *string `json:"title"`

	// creation date of the entry
	// Required: true
	// Format: date
	CreationDate *strfmt.Date `json:"creation_date"`

	// entry authors
	// Required: true
	Authors []string `json:"authors"`

	// city
	City string `json:"city,omitempty"`

	// department
	Department string `json:"department,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// natures
	Natures []string `json:"natures"`

	// professions
	Professions []string `json:"professions"`

	// images ID of the monument lieu
	Medias []*Media `json:"medias"`

	// time period of the monument lieu
	Centuries []string `json:"centuries"`
}

// Validate validates this pending documents
func (m *PendingDocuments) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedias(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PendingDocuments) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *PendingDocuments) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

func (m *PendingDocuments) validateCreationDate(formats strfmt.Registry) error {

	if err := validate.Required("creation_date", "body", m.CreationDate); err != nil {
		return err
	}

	if err := validate.FormatOf("creation_date", "body", "date", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PendingDocuments) validateAuthors(formats strfmt.Registry) error {

	if err := validate.Required("authors", "body", m.Authors); err != nil {
		return err
	}

	return nil
}

func (m *PendingDocuments) validateMedias(formats strfmt.Registry) error {
	if swag.IsZero(m.Medias) { // not required
		return nil
	}

	for i := 0; i < len(m.Medias); i++ {
		if swag.IsZero(m.Medias[i]) { // not required
			continue
		}

		if m.Medias[i] != nil {
			if err := m.Medias[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this pending documents based on the context it is used
func (m *PendingDocuments) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMedias(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PendingDocuments) contextValidateMedias(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Medias); i++ {

		if m.Medias[i] != nil {

			if swag.IsZero(m.Medias[i]) { // not required
				return nil
			}

			if err := m.Medias[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PendingDocuments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PendingDocuments) UnmarshalBinary(b []byte) error {
	var res PendingDocuments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
