// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAdminUserInfo get admin user info
//
// swagger:model GetAdminUserInfo
type GetAdminUserInfo struct {

	// id
	// Required: true
	// Format: uuid
	ID *strfmt.UUID `json:"id"`

	// First name
	// Required: true
	Firstname *string `json:"firstname"`

	// Last name
	// Required: true
	Lastname *string `json:"lastname"`

	// Email of contributor
	// Required: true
	// Format: email
	Mail *strfmt.Email `json:"mail"`

	// Email confirmed or not
	MailConfirm bool `json:"mail_confirm,omitempty"`

	// phone
	// Max Length: 20
	Phone string `json:"phone,omitempty"`

	// organization
	Organization string `json:"organization,omitempty"`

	// domain
	// Enum: ["ART","ARCHITECTURE","MEDIEVAL","ARCHEOLOGIE","PATRIMOINE","THEOLOGIE","PELERINAGE","AUTRE"]
	Domain string `json:"domain,omitempty"`

	// last login
	// Format: date-time
	LastLogin strfmt.DateTime `json:"last_login,omitempty"`

	// First name of the validator
	ValidatedByFirstname string `json:"validated_by_firstname,omitempty"`

	// Last name of the validator
	ValidatedByLastname string `json:"validated_by_lastname,omitempty"`

	// Email of the validator
	// Format: email
	ValidatedByMail strfmt.Email `json:"validated_by_mail,omitempty"`

	// grade
	// Required: true
	// Enum: ["PENDING","ACTIVE","ADMIN"]
	Grade *string `json:"grade"`

	// creation date of the entry
	// Required: true
	// Format: date-time
	CreationDate *strfmt.DateTime `json:"creation_date"`
}

// Validate validates this get admin user info
func (m *GetAdminUserInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhone(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidatedByMail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGrade(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAdminUserInfo) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validateFirstname(formats strfmt.Registry) error {

	if err := validate.Required("firstname", "body", m.Firstname); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validateLastname(formats strfmt.Registry) error {

	if err := validate.Required("lastname", "body", m.Lastname); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validateMail(formats strfmt.Registry) error {

	if err := validate.Required("mail", "body", m.Mail); err != nil {
		return err
	}

	if err := validate.FormatOf("mail", "body", "email", m.Mail.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validatePhone(formats strfmt.Registry) error {
	if swag.IsZero(m.Phone) { // not required
		return nil
	}

	if err := validate.MaxLength("phone", "body", m.Phone, 20); err != nil {
		return err
	}

	return nil
}

var getAdminUserInfoTypeDomainPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ART","ARCHITECTURE","MEDIEVAL","ARCHEOLOGIE","PATRIMOINE","THEOLOGIE","PELERINAGE","AUTRE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAdminUserInfoTypeDomainPropEnum = append(getAdminUserInfoTypeDomainPropEnum, v)
	}
}

const (

	// GetAdminUserInfoDomainART captures enum value "ART"
	GetAdminUserInfoDomainART string = "ART"

	// GetAdminUserInfoDomainARCHITECTURE captures enum value "ARCHITECTURE"
	GetAdminUserInfoDomainARCHITECTURE string = "ARCHITECTURE"

	// GetAdminUserInfoDomainMEDIEVAL captures enum value "MEDIEVAL"
	GetAdminUserInfoDomainMEDIEVAL string = "MEDIEVAL"

	// GetAdminUserInfoDomainARCHEOLOGIE captures enum value "ARCHEOLOGIE"
	GetAdminUserInfoDomainARCHEOLOGIE string = "ARCHEOLOGIE"

	// GetAdminUserInfoDomainPATRIMOINE captures enum value "PATRIMOINE"
	GetAdminUserInfoDomainPATRIMOINE string = "PATRIMOINE"

	// GetAdminUserInfoDomainTHEOLOGIE captures enum value "THEOLOGIE"
	GetAdminUserInfoDomainTHEOLOGIE string = "THEOLOGIE"

	// GetAdminUserInfoDomainPELERINAGE captures enum value "PELERINAGE"
	GetAdminUserInfoDomainPELERINAGE string = "PELERINAGE"

	// GetAdminUserInfoDomainAUTRE captures enum value "AUTRE"
	GetAdminUserInfoDomainAUTRE string = "AUTRE"
)

// prop value enum
func (m *GetAdminUserInfo) validateDomainEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAdminUserInfoTypeDomainPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetAdminUserInfo) validateDomain(formats strfmt.Registry) error {
	if swag.IsZero(m.Domain) { // not required
		return nil
	}

	// value enum
	if err := m.validateDomainEnum("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validateLastLogin(formats strfmt.Registry) error {
	if swag.IsZero(m.LastLogin) { // not required
		return nil
	}

	if err := validate.FormatOf("last_login", "body", "date-time", m.LastLogin.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validateValidatedByMail(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidatedByMail) { // not required
		return nil
	}

	if err := validate.FormatOf("validated_by_mail", "body", "email", m.ValidatedByMail.String(), formats); err != nil {
		return err
	}

	return nil
}

var getAdminUserInfoTypeGradePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PENDING","ACTIVE","ADMIN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAdminUserInfoTypeGradePropEnum = append(getAdminUserInfoTypeGradePropEnum, v)
	}
}

const (

	// GetAdminUserInfoGradePENDING captures enum value "PENDING"
	GetAdminUserInfoGradePENDING string = "PENDING"

	// GetAdminUserInfoGradeACTIVE captures enum value "ACTIVE"
	GetAdminUserInfoGradeACTIVE string = "ACTIVE"

	// GetAdminUserInfoGradeADMIN captures enum value "ADMIN"
	GetAdminUserInfoGradeADMIN string = "ADMIN"
)

// prop value enum
func (m *GetAdminUserInfo) validateGradeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAdminUserInfoTypeGradePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetAdminUserInfo) validateGrade(formats strfmt.Registry) error {

	if err := validate.Required("grade", "body", m.Grade); err != nil {
		return err
	}

	// value enum
	if err := m.validateGradeEnum("grade", "body", *m.Grade); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminUserInfo) validateCreationDate(formats strfmt.Registry) error {

	if err := validate.Required("creation_date", "body", m.CreationDate); err != nil {
		return err
	}

	if err := validate.FormatOf("creation_date", "body", "date-time", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get admin user info based on context it is used
func (m *GetAdminUserInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAdminUserInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAdminUserInfo) UnmarshalBinary(b []byte) error {
	var res GetAdminUserInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
