// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MobilierImageCreationBody mobilier image creation body
//
// swagger:model MobilierImageCreationBody
type MobilierImageCreationBody struct {

	// Title of the monument lieu
	// Required: true
	Title *string `json:"title"`

	// centuries
	Centuries []int32 `json:"centuries"`

	// medias
	Medias []int32 `json:"medias"`

	// city
	City int32 `json:"city,omitempty"`

	// department
	Department int32 `json:"department,omitempty"`

	// region
	Region int32 `json:"region,omitempty"`

	// country
	Country int32 `json:"country,omitempty"`

	// themes
	Themes []int32 `json:"themes"`

	// contributors
	Contributors []string `json:"contributors"`

	// source
	Source string `json:"source,omitempty"`

	// description
	// Required: true
	Description *string `json:"description"`

	// inscription
	Inscription string `json:"inscription,omitempty"`

	// history
	History string `json:"history,omitempty"`

	// bibliography
	Bibliography string `json:"bibliography,omitempty"`

	// conservation states
	ConservationStates []int32 `json:"conservationStates"`

	// is protected
	IsProtected bool `json:"isProtected,omitempty"`

	// protection comment
	ProtectionComment string `json:"protectionComment,omitempty"`

	// materials
	Materials []int32 `json:"materials"`

	// techniques
	Techniques []int32 `json:"techniques"`

	// natures
	Natures []int32 `json:"natures"`

	// origin place
	OriginPlace string `json:"originPlace,omitempty"`

	// present place
	PresentPlace string `json:"presentPlace,omitempty"`

	// linked monuments lieux
	LinkedMonumentsLieux []int32 `json:"linkedMonumentsLieux"`

	// linked pers morales
	LinkedPersMorales []int32 `json:"linkedPersMorales"`

	// linked pers physiques
	LinkedPersPhysiques []int32 `json:"linkedPersPhysiques"`
}

// Validate validates this mobilier image creation body
func (m *MobilierImageCreationBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MobilierImageCreationBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

func (m *MobilierImageCreationBody) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this mobilier image creation body based on context it is used
func (m *MobilierImageCreationBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MobilierImageCreationBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MobilierImageCreationBody) UnmarshalBinary(b []byte) error {
	var res MobilierImageCreationBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
