// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommuneFilter commune filter
//
// swagger:model CommuneFilter
type CommuneFilter struct {
	BasicFilter

	// department
	Department *DepartmentFilter `json:"department,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *CommuneFilter) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BasicFilter
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BasicFilter = aO0

	// now for regular properties
	var propsCommuneFilter struct {
		Department *DepartmentFilter `json:"department,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsCommuneFilter); err != nil {
		return err
	}
	m.Department = propsCommuneFilter.Department

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m CommuneFilter) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.BasicFilter)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsCommuneFilter struct {
		Department *DepartmentFilter `json:"department,omitempty"`
	}
	propsCommuneFilter.Department = m.Department

	jsonDataPropsCommuneFilter, errCommuneFilter := swag.WriteJSON(propsCommuneFilter)
	if errCommuneFilter != nil {
		return nil, errCommuneFilter
	}
	_parts = append(_parts, jsonDataPropsCommuneFilter)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this commune filter
func (m *CommuneFilter) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BasicFilter
	if err := m.BasicFilter.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepartment(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CommuneFilter) validateDepartment(formats strfmt.Registry) error {
	if swag.IsZero(m.Department) { // not required
		return nil
	}

	if m.Department != nil {
		if err := m.Department.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("department")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("department")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this commune filter based on the context it is used
func (m *CommuneFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BasicFilter
	if err := m.BasicFilter.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepartment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CommuneFilter) contextValidateDepartment(ctx context.Context, formats strfmt.Registry) error {

	if m.Department != nil {

		if swag.IsZero(m.Department) { // not required
			return nil
		}

		if err := m.Department.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("department")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("department")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CommuneFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommuneFilter) UnmarshalBinary(b []byte) error {
	var res CommuneFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
