// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PersonnePhysique personne physique
//
// swagger:model PersonnePhysique
type PersonnePhysique struct {

	// ID of the individual
	ID int32 `json:"id,omitempty"`

	// First name of the individual
	Firstname string `json:"firstname,omitempty"`

	// Date of birth or approx
	Birthdate string `json:"birthdate,omitempty"`

	// Date of death
	Death string `json:"death,omitempty"`

	// attestation
	Attestation string `json:"attestation,omitempty"`

	// historical period
	HistoricalPeriod []string `json:"historical_period"`

	// bibliography of the individual
	Bibliography string `json:"bibliography,omitempty"`

	// biographical elements
	BiographicalElements string `json:"biographical_elements,omitempty"`

	// pilgrimage element
	PilgrimageElement string `json:"pilgrimage_element,omitempty"`

	// vow commutation
	Commutation string `json:"commutation,omitempty"`

	// sources of the legal entity
	Sources string `json:"sources,omitempty"`

	// creation date of the entry
	// Format: date
	CreationDate strfmt.Date `json:"creation_date,omitempty"`

	// update date of the entry
	// Format: date
	UpdateDate strfmt.Date `json:"update_date,omitempty"`

	// is entry published
	Published bool `json:"published,omitempty"`

	// name of the contributors
	Contributors string `json:"contributors,omitempty"`

	// Comment
	Comment string `json:"comment,omitempty"`

	// entry authors
	Authors []string `json:"authors"`

	// city of the individual
	City string `json:"city,omitempty"`

	// department of the individual
	Department string `json:"department,omitempty"`

	// region of the individual
	Region string `json:"region,omitempty"`

	// country of the individual
	Country string `json:"country,omitempty"`

	// travels
	Travels []string `json:"travels"`

	// professions
	Professions []string `json:"professions"`

	// event nature
	EventNature string `json:"event_nature,omitempty"`

	// images ID of the monument lieu
	Medias []*Media `json:"medias"`

	// time period of the monument lieu
	Centuries []string `json:"centuries"`

	// linked monuments places
	LinkedMonumentsPlaces []int32 `json:"linked_monuments_places"`

	// linked legal entities
	LinkedLegalEntities []int32 `json:"linked_legal_entities"`

	// linked furniture images
	LinkedFurnitureImages []int32 `json:"linked_furniture_images"`

	// themes
	Themes []string `json:"themes"`
}

// Validate validates this personne physique
func (m *PersonnePhysique) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedias(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonnePhysique) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_date", "body", "date", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PersonnePhysique) validateUpdateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("update_date", "body", "date", m.UpdateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PersonnePhysique) validateMedias(formats strfmt.Registry) error {
	if swag.IsZero(m.Medias) { // not required
		return nil
	}

	for i := 0; i < len(m.Medias); i++ {
		if swag.IsZero(m.Medias[i]) { // not required
			continue
		}

		if m.Medias[i] != nil {
			if err := m.Medias[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this personne physique based on the context it is used
func (m *PersonnePhysique) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMedias(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonnePhysique) contextValidateMedias(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Medias); i++ {

		if m.Medias[i] != nil {

			if swag.IsZero(m.Medias[i]) { // not required
				return nil
			}

			if err := m.Medias[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PersonnePhysique) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonnePhysique) UnmarshalBinary(b []byte) error {
	var res PersonnePhysique
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
