// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PersonnePhysiqueCreationBody personne physique creation body
//
// swagger:model PersonnePhysiqueCreationBody
type PersonnePhysiqueCreationBody struct {

	// Title of the monument lieu
	// Required: true
	Title *string `json:"title"`

	// centuries
	Centuries []int32 `json:"centuries"`

	// medias
	Medias []int32 `json:"medias"`

	// city
	City int32 `json:"city,omitempty"`

	// department
	Department int32 `json:"department,omitempty"`

	// region
	Region int32 `json:"region,omitempty"`

	// country
	Country int32 `json:"country,omitempty"`

	// themes
	Themes []int32 `json:"themes"`

	// contributors
	Contributors []string `json:"contributors"`

	// source
	Source string `json:"source,omitempty"`

	// birthday
	Birthday string `json:"birthday,omitempty"`

	// death
	Death string `json:"death,omitempty"`

	// attestation
	Attestation string `json:"attestation,omitempty"`

	// historical periods
	HistoricalPeriods []int32 `json:"historical_periods"`

	// professions
	Professions []int32 `json:"professions"`

	// biographical elements
	BiographicalElements string `json:"biographical_elements,omitempty"`

	// pilgrimage elements
	PilgrimageElements string `json:"pilgrimage_elements,omitempty"`

	// travels
	Travels []int32 `json:"travels"`

	// nature
	Nature string `json:"nature,omitempty"`

	// commutation
	Commutation string `json:"commutation,omitempty"`

	// bibliography
	Bibliography string `json:"bibliography,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// linked monuments lieux
	LinkedMonumentsLieux []int32 `json:"linkedMonumentsLieux"`

	// linked mobiliers images
	LinkedMobiliersImages []int32 `json:"linkedMobiliersImages"`

	// linked pers morales
	LinkedPersMorales []int32 `json:"linkedPersMorales"`
}

// Validate validates this personne physique creation body
func (m *PersonnePhysiqueCreationBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonnePhysiqueCreationBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this personne physique creation body based on context it is used
func (m *PersonnePhysiqueCreationBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PersonnePhysiqueCreationBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonnePhysiqueCreationBody) UnmarshalBinary(b []byte) error {
	var res PersonnePhysiqueCreationBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
