// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MonumentLieu monument lieu
//
// swagger:model MonumentLieu
type MonumentLieu struct {

	// ID of the monument lieu
	ID int32 `json:"id,omitempty"`

	// Title of the monument lieu
	Title string `json:"title,omitempty"`

	// Description of the monument lieu
	Description string `json:"description,omitempty"`

	// History of the monument lieu
	History string `json:"history,omitempty"`

	// geolocation of the monument lieu
	Geolocation string `json:"geolocation,omitempty"`

	// bibliography of the monument lieu
	Bibliography string `json:"bibliography,omitempty"`

	// creation date of the entry
	// Format: date
	CreationDate strfmt.Date `json:"creation_date,omitempty"`

	// update date of the entry
	// Format: date
	UpdateDate strfmt.Date `json:"update_date,omitempty"`

	// is entry published
	Published bool `json:"published,omitempty"`

	// name of the contributors
	Contributors string `json:"contributors,omitempty"`

	// is it protected
	Protected bool `json:"protected,omitempty"`

	// protection comment
	ProtectionComment string `json:"protection_comment,omitempty"`

	// entry authors
	Authors []*BasicFilter `json:"authors"`

	// Sources of the information
	Sources string `json:"sources,omitempty"`

	// city of the monument lieu
	City *BasicFilter `json:"city,omitempty"`

	// department of the monument lieu
	Department *BasicFilter `json:"department,omitempty"`

	// region of the monument lieu
	Region *BasicFilter `json:"region,omitempty"`

	// country of the monument lieu
	Country *BasicFilter `json:"country,omitempty"`

	// conservation states
	Conservation []*BasicFilter `json:"conservation"`

	// materials used for the monument lieu
	Materials []*BasicFilter `json:"materials"`

	// natures of the monument lieu
	Natures []*BasicFilter `json:"natures"`

	// images ID of the monument lieu
	Medias []*Media `json:"medias"`

	// time period of the monument lieu
	Centuries []*BasicFilter `json:"centuries"`

	// linked furniture images
	LinkedFurnitureImages []int32 `json:"linked_furniture_images"`

	// linked individuals
	LinkedIndividuals []int32 `json:"linked_individuals"`

	// linked legal entities
	LinkedLegalEntities []int32 `json:"linked_legal_entities"`

	// themes
	Themes []*BasicFilter `json:"themes"`

	// parent id
	ParentID int32 `json:"parent_id,omitempty"`

	// comment of the temoin
	TemoinComment string `json:"temoinComment,omitempty"`
}

// Validate validates this monument lieu
func (m *MonumentLieu) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepartment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConservation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaterials(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedias(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCenturies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThemes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MonumentLieu) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_date", "body", "date", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *MonumentLieu) validateUpdateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("update_date", "body", "date", m.UpdateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *MonumentLieu) validateAuthors(formats strfmt.Registry) error {
	if swag.IsZero(m.Authors) { // not required
		return nil
	}

	for i := 0; i < len(m.Authors); i++ {
		if swag.IsZero(m.Authors[i]) { // not required
			continue
		}

		if m.Authors[i] != nil {
			if err := m.Authors[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("authors" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("authors" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) validateCity(formats strfmt.Registry) error {
	if swag.IsZero(m.City) { // not required
		return nil
	}

	if m.City != nil {
		if err := m.City.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("city")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("city")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) validateDepartment(formats strfmt.Registry) error {
	if swag.IsZero(m.Department) { // not required
		return nil
	}

	if m.Department != nil {
		if err := m.Department.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("department")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("department")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) validateRegion(formats strfmt.Registry) error {
	if swag.IsZero(m.Region) { // not required
		return nil
	}

	if m.Region != nil {
		if err := m.Region.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("region")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("region")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) validateCountry(formats strfmt.Registry) error {
	if swag.IsZero(m.Country) { // not required
		return nil
	}

	if m.Country != nil {
		if err := m.Country.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("country")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("country")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) validateConservation(formats strfmt.Registry) error {
	if swag.IsZero(m.Conservation) { // not required
		return nil
	}

	for i := 0; i < len(m.Conservation); i++ {
		if swag.IsZero(m.Conservation[i]) { // not required
			continue
		}

		if m.Conservation[i] != nil {
			if err := m.Conservation[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("conservation" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("conservation" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) validateMaterials(formats strfmt.Registry) error {
	if swag.IsZero(m.Materials) { // not required
		return nil
	}

	for i := 0; i < len(m.Materials); i++ {
		if swag.IsZero(m.Materials[i]) { // not required
			continue
		}

		if m.Materials[i] != nil {
			if err := m.Materials[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("materials" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("materials" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) validateNatures(formats strfmt.Registry) error {
	if swag.IsZero(m.Natures) { // not required
		return nil
	}

	for i := 0; i < len(m.Natures); i++ {
		if swag.IsZero(m.Natures[i]) { // not required
			continue
		}

		if m.Natures[i] != nil {
			if err := m.Natures[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("natures" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("natures" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) validateMedias(formats strfmt.Registry) error {
	if swag.IsZero(m.Medias) { // not required
		return nil
	}

	for i := 0; i < len(m.Medias); i++ {
		if swag.IsZero(m.Medias[i]) { // not required
			continue
		}

		if m.Medias[i] != nil {
			if err := m.Medias[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) validateCenturies(formats strfmt.Registry) error {
	if swag.IsZero(m.Centuries) { // not required
		return nil
	}

	for i := 0; i < len(m.Centuries); i++ {
		if swag.IsZero(m.Centuries[i]) { // not required
			continue
		}

		if m.Centuries[i] != nil {
			if err := m.Centuries[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("centuries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("centuries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) validateThemes(formats strfmt.Registry) error {
	if swag.IsZero(m.Themes) { // not required
		return nil
	}

	for i := 0; i < len(m.Themes); i++ {
		if swag.IsZero(m.Themes[i]) { // not required
			continue
		}

		if m.Themes[i] != nil {
			if err := m.Themes[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("themes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("themes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this monument lieu based on the context it is used
func (m *MonumentLieu) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepartment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRegion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCountry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConservation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMaterials(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNatures(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMedias(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCenturies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateThemes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MonumentLieu) contextValidateAuthors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Authors); i++ {

		if m.Authors[i] != nil {

			if swag.IsZero(m.Authors[i]) { // not required
				return nil
			}

			if err := m.Authors[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("authors" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("authors" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) contextValidateCity(ctx context.Context, formats strfmt.Registry) error {

	if m.City != nil {

		if swag.IsZero(m.City) { // not required
			return nil
		}

		if err := m.City.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("city")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("city")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) contextValidateDepartment(ctx context.Context, formats strfmt.Registry) error {

	if m.Department != nil {

		if swag.IsZero(m.Department) { // not required
			return nil
		}

		if err := m.Department.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("department")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("department")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) contextValidateRegion(ctx context.Context, formats strfmt.Registry) error {

	if m.Region != nil {

		if swag.IsZero(m.Region) { // not required
			return nil
		}

		if err := m.Region.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("region")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("region")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) contextValidateCountry(ctx context.Context, formats strfmt.Registry) error {

	if m.Country != nil {

		if swag.IsZero(m.Country) { // not required
			return nil
		}

		if err := m.Country.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("country")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("country")
			}

			return err
		}
	}

	return nil
}

func (m *MonumentLieu) contextValidateConservation(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Conservation); i++ {

		if m.Conservation[i] != nil {

			if swag.IsZero(m.Conservation[i]) { // not required
				return nil
			}

			if err := m.Conservation[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("conservation" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("conservation" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) contextValidateMaterials(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Materials); i++ {

		if m.Materials[i] != nil {

			if swag.IsZero(m.Materials[i]) { // not required
				return nil
			}

			if err := m.Materials[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("materials" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("materials" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) contextValidateNatures(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Natures); i++ {

		if m.Natures[i] != nil {

			if swag.IsZero(m.Natures[i]) { // not required
				return nil
			}

			if err := m.Natures[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("natures" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("natures" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) contextValidateMedias(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Medias); i++ {

		if m.Medias[i] != nil {

			if swag.IsZero(m.Medias[i]) { // not required
				return nil
			}

			if err := m.Medias[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) contextValidateCenturies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Centuries); i++ {

		if m.Centuries[i] != nil {

			if swag.IsZero(m.Centuries[i]) { // not required
				return nil
			}

			if err := m.Centuries[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("centuries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("centuries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *MonumentLieu) contextValidateThemes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Themes); i++ {

		if m.Themes[i] != nil {

			if swag.IsZero(m.Themes[i]) { // not required
				return nil
			}

			if err := m.Themes[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("themes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("themes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MonumentLieu) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MonumentLieu) UnmarshalBinary(b []byte) error {
	var res MonumentLieu
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
