// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetUserInfo get user info
//
// swagger:model GetUserInfo
type GetUserInfo struct {

	// id
	// Required: true
	// Format: uuid
	ID *strfmt.UUID `json:"id"`

	// First name
	// Required: true
	Firstname *string `json:"firstname"`

	// Last name
	// Required: true
	Lastname *string `json:"lastname"`

	// Email of contributor
	// Required: true
	// Format: email
	Mail *strfmt.Email `json:"mail"`

	// phone
	// Max Length: 20
	Phone string `json:"phone,omitempty"`

	// organization
	Organization string `json:"organization,omitempty"`

	// domain
	// Required: true
	// Enum: ["ART","ARCHITECTURE","MEDIEVAL","ARCHEOLOGIE","PATRIMOINE","THEOLOGIE","PELERINAGE","AUTRE"]
	Domain *string `json:"domain"`

	// motivation
	// Required: true
	Motivation *string `json:"motivation"`

	// creation date of the entry
	// Format: date
	CreationDate strfmt.Date `json:"creation_date,omitempty"`
}

// Validate validates this get user info
func (m *GetUserInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhone(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMotivation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetUserInfo) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetUserInfo) validateFirstname(formats strfmt.Registry) error {

	if err := validate.Required("firstname", "body", m.Firstname); err != nil {
		return err
	}

	return nil
}

func (m *GetUserInfo) validateLastname(formats strfmt.Registry) error {

	if err := validate.Required("lastname", "body", m.Lastname); err != nil {
		return err
	}

	return nil
}

func (m *GetUserInfo) validateMail(formats strfmt.Registry) error {

	if err := validate.Required("mail", "body", m.Mail); err != nil {
		return err
	}

	if err := validate.FormatOf("mail", "body", "email", m.Mail.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetUserInfo) validatePhone(formats strfmt.Registry) error {
	if swag.IsZero(m.Phone) { // not required
		return nil
	}

	if err := validate.MaxLength("phone", "body", m.Phone, 20); err != nil {
		return err
	}

	return nil
}

var getUserInfoTypeDomainPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ART","ARCHITECTURE","MEDIEVAL","ARCHEOLOGIE","PATRIMOINE","THEOLOGIE","PELERINAGE","AUTRE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getUserInfoTypeDomainPropEnum = append(getUserInfoTypeDomainPropEnum, v)
	}
}

const (

	// GetUserInfoDomainART captures enum value "ART"
	GetUserInfoDomainART string = "ART"

	// GetUserInfoDomainARCHITECTURE captures enum value "ARCHITECTURE"
	GetUserInfoDomainARCHITECTURE string = "ARCHITECTURE"

	// GetUserInfoDomainMEDIEVAL captures enum value "MEDIEVAL"
	GetUserInfoDomainMEDIEVAL string = "MEDIEVAL"

	// GetUserInfoDomainARCHEOLOGIE captures enum value "ARCHEOLOGIE"
	GetUserInfoDomainARCHEOLOGIE string = "ARCHEOLOGIE"

	// GetUserInfoDomainPATRIMOINE captures enum value "PATRIMOINE"
	GetUserInfoDomainPATRIMOINE string = "PATRIMOINE"

	// GetUserInfoDomainTHEOLOGIE captures enum value "THEOLOGIE"
	GetUserInfoDomainTHEOLOGIE string = "THEOLOGIE"

	// GetUserInfoDomainPELERINAGE captures enum value "PELERINAGE"
	GetUserInfoDomainPELERINAGE string = "PELERINAGE"

	// GetUserInfoDomainAUTRE captures enum value "AUTRE"
	GetUserInfoDomainAUTRE string = "AUTRE"
)

// prop value enum
func (m *GetUserInfo) validateDomainEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getUserInfoTypeDomainPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetUserInfo) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	// value enum
	if err := m.validateDomainEnum("domain", "body", *m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *GetUserInfo) validateMotivation(formats strfmt.Registry) error {

	if err := validate.Required("motivation", "body", m.Motivation); err != nil {
		return err
	}

	return nil
}

func (m *GetUserInfo) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_date", "body", "date", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get user info based on context it is used
func (m *GetUserInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetUserInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetUserInfo) UnmarshalBinary(b []byte) error {
	var res GetUserInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
