// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PersonnesPhysiquesListFilters personnes physiques list filters
//
// swagger:model PersonnesPhysiquesListFilters
type PersonnesPhysiquesListFilters struct {

	// countries
	Countries []int32 `json:"countries"`

	// regions
	Regions []int32 `json:"regions"`

	// departments
	Departments []int32 `json:"departments"`

	// cities
	Cities []int32 `json:"cities"`

	// centuries
	Centuries []int32 `json:"centuries"`

	// professions
	Professions []int32 `json:"professions"`

	// authors
	Authors []int32 `json:"authors"`

	// travels
	Travels []int32 `json:"travels"`

	// furniture
	Furniture []int32 `json:"furniture"`

	// legal entities
	LegalEntities []int32 `json:"legal_entities"`

	// places
	Places []int32 `json:"places"`
}

// Validate validates this personnes physiques list filters
func (m *PersonnesPhysiquesListFilters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this personnes physiques list filters based on context it is used
func (m *PersonnesPhysiquesListFilters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PersonnesPhysiquesListFilters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonnesPhysiquesListFilters) UnmarshalBinary(b []byte) error {
	var res PersonnesPhysiquesListFilters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
