// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchUsersBody patch users body
//
// swagger:model PatchUsersBody
type PatchUsersBody struct {

	// action
	// Required: true
	// Enum: ["activate","reject"]
	Action *string `json:"action"`
}

// Validate validates this patch users body
func (m *PatchUsersBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var patchUsersBodyTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["activate","reject"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		patchUsersBodyTypeActionPropEnum = append(patchUsersBodyTypeActionPropEnum, v)
	}
}

const (

	// PatchUsersBodyActionActivate captures enum value "activate"
	PatchUsersBodyActionActivate string = "activate"

	// PatchUsersBodyActionReject captures enum value "reject"
	PatchUsersBodyActionReject string = "reject"
)

// prop value enum
func (m *PatchUsersBody) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, patchUsersBodyTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PatchUsersBody) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this patch users body based on context it is used
func (m *PatchUsersBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchUsersBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchUsersBody) UnmarshalBinary(b []byte) error {
	var res PatchUsersBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
