// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PersonnesMoralesListFilters personnes morales list filters
//
// swagger:model PersonnesMoralesListFilters
type PersonnesMoralesListFilters struct {

	// countries
	Countries []int32 `json:"countries"`

	// regions
	Regions []int32 `json:"regions"`

	// departments
	Departments []int32 `json:"departments"`

	// cities
	Cities []int32 `json:"cities"`

	// centuries
	Centuries []int32 `json:"centuries"`

	// natures
	Natures []int32 `json:"natures"`

	// authors
	Authors []int32 `json:"authors"`

	// furniture
	Furniture []int32 `json:"furniture"`

	// individuals
	Individuals []int32 `json:"individuals"`

	// places
	Places []int32 `json:"places"`
}

// Validate validates this personnes morales list filters
func (m *PersonnesMoralesListFilters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this personnes morales list filters based on context it is used
func (m *PersonnesMoralesListFilters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PersonnesMoralesListFilters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonnesMoralesListFilters) UnmarshalBinary(b []byte) error {
	var res PersonnesMoralesListFilters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
