// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PersonnePhysique personne physique
//
// swagger:model PersonnePhysique
type PersonnePhysique struct {

	// ID of the individual
	ID int32 `json:"id,omitempty"`

	// First name of the individual
	Firstname string `json:"firstname,omitempty"`

	// Date of birth or approx
	Birthdate string `json:"birthdate,omitempty"`

	// Date of death
	Death string `json:"death,omitempty"`

	// attestation
	Attestation string `json:"attestation,omitempty"`

	// historical period
	HistoricalPeriod []*BasicFilter `json:"historical_period"`

	// bibliography of the individual
	Bibliography string `json:"bibliography,omitempty"`

	// biographical elements
	BiographicalElements string `json:"biographical_elements,omitempty"`

	// pilgrimage element
	PilgrimageElement string `json:"pilgrimage_element,omitempty"`

	// vow commutation
	Commutation string `json:"commutation,omitempty"`

	// sources of the legal entity
	Sources string `json:"sources,omitempty"`

	// creation date of the entry (null when the record has no creation nor update date)
	// Format: date
	CreationDate *strfmt.Date `json:"creation_date,omitempty"`

	// update date of the entry (null when the record has no update date)
	// Format: date
	UpdateDate *strfmt.Date `json:"update_date,omitempty"`

	// is entry published
	Published bool `json:"published,omitempty"`

	// name of the contributors
	Contributors string `json:"contributors,omitempty"`

	// Comment
	Comment string `json:"comment,omitempty"`

	// entry authors
	Authors []*BasicFilter `json:"authors"`

	// city of the individual
	City *BasicFilter `json:"city,omitempty"`

	// department of the individual
	Department *BasicFilter `json:"department,omitempty"`

	// region of the individual
	Region *BasicFilter `json:"region,omitempty"`

	// country of the individual
	Country *BasicFilter `json:"country,omitempty"`

	// travels
	Travels []*BasicFilter `json:"travels"`

	// professions
	Professions []*BasicFilter `json:"professions"`

	// event nature
	EventNature string `json:"event_nature,omitempty"`

	// historiography
	Historiography string `json:"historiography,omitempty"`

	// events
	Evenements string `json:"evenements,omitempty"`

	// preparations
	Preparatifs string `json:"preparatifs,omitempty"`

	// path followed
	CheminSuivi string `json:"chemin_suivi,omitempty"`

	// arrival
	Arrivee string `json:"arrivee,omitempty"`

	// return
	Retour string `json:"retour,omitempty"`

	// non-execution
	NonExecution string `json:"non_execution,omitempty"`

	// age
	Age string `json:"age,omitempty"`

	// group composition
	CompositionGroupe string `json:"composition_groupe,omitempty"`

	// images ID of the monument lieu
	Medias []*Media `json:"medias"`

	// time period of the monument lieu
	Centuries []*BasicFilter `json:"centuries"`

	// linked monuments places
	LinkedMonumentsPlaces []int32 `json:"linked_monuments_places"`

	// linked legal entities
	LinkedLegalEntities []int32 `json:"linked_legal_entities"`

	// linked furniture images
	LinkedFurnitureImages []int32 `json:"linked_furniture_images"`

	// linked individuals
	LinkedIndividuals []int32 `json:"linked_individuals"`

	// themes
	Themes []*BasicFilter `json:"themes"`

	// parent id
	ParentID int32 `json:"parent_id,omitempty"`

	// publication status of the entry
	// Enum: ["DRAFT","PENDING","PUBLISHED"]
	PublicationStatus string `json:"publication_status,omitempty"`

	// comment of the temoin
	TemoinComment string `json:"temoinComment,omitempty"`
}

// Validate validates this personne physique
func (m *PersonnePhysique) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHistoricalPeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepartment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTravels(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfessions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedias(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCenturies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThemes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicationStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonnePhysique) validateHistoricalPeriod(formats strfmt.Registry) error {
	if swag.IsZero(m.HistoricalPeriod) { // not required
		return nil
	}

	for i := 0; i < len(m.HistoricalPeriod); i++ {
		if swag.IsZero(m.HistoricalPeriod[i]) { // not required
			continue
		}

		if m.HistoricalPeriod[i] != nil {
			if err := m.HistoricalPeriod[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("historical_period" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("historical_period" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_date", "body", "date", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PersonnePhysique) validateUpdateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("update_date", "body", "date", m.UpdateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PersonnePhysique) validateAuthors(formats strfmt.Registry) error {
	if swag.IsZero(m.Authors) { // not required
		return nil
	}

	for i := 0; i < len(m.Authors); i++ {
		if swag.IsZero(m.Authors[i]) { // not required
			continue
		}

		if m.Authors[i] != nil {
			if err := m.Authors[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("authors" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("authors" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) validateCity(formats strfmt.Registry) error {
	if swag.IsZero(m.City) { // not required
		return nil
	}

	if m.City != nil {
		if err := m.City.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("city")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("city")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) validateDepartment(formats strfmt.Registry) error {
	if swag.IsZero(m.Department) { // not required
		return nil
	}

	if m.Department != nil {
		if err := m.Department.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("department")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("department")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) validateRegion(formats strfmt.Registry) error {
	if swag.IsZero(m.Region) { // not required
		return nil
	}

	if m.Region != nil {
		if err := m.Region.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("region")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("region")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) validateCountry(formats strfmt.Registry) error {
	if swag.IsZero(m.Country) { // not required
		return nil
	}

	if m.Country != nil {
		if err := m.Country.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("country")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("country")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) validateTravels(formats strfmt.Registry) error {
	if swag.IsZero(m.Travels) { // not required
		return nil
	}

	for i := 0; i < len(m.Travels); i++ {
		if swag.IsZero(m.Travels[i]) { // not required
			continue
		}

		if m.Travels[i] != nil {
			if err := m.Travels[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("travels" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("travels" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) validateProfessions(formats strfmt.Registry) error {
	if swag.IsZero(m.Professions) { // not required
		return nil
	}

	for i := 0; i < len(m.Professions); i++ {
		if swag.IsZero(m.Professions[i]) { // not required
			continue
		}

		if m.Professions[i] != nil {
			if err := m.Professions[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("professions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("professions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) validateMedias(formats strfmt.Registry) error {
	if swag.IsZero(m.Medias) { // not required
		return nil
	}

	for i := 0; i < len(m.Medias); i++ {
		if swag.IsZero(m.Medias[i]) { // not required
			continue
		}

		if m.Medias[i] != nil {
			if err := m.Medias[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) validateCenturies(formats strfmt.Registry) error {
	if swag.IsZero(m.Centuries) { // not required
		return nil
	}

	for i := 0; i < len(m.Centuries); i++ {
		if swag.IsZero(m.Centuries[i]) { // not required
			continue
		}

		if m.Centuries[i] != nil {
			if err := m.Centuries[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("centuries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("centuries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) validateThemes(formats strfmt.Registry) error {
	if swag.IsZero(m.Themes) { // not required
		return nil
	}

	for i := 0; i < len(m.Themes); i++ {
		if swag.IsZero(m.Themes[i]) { // not required
			continue
		}

		if m.Themes[i] != nil {
			if err := m.Themes[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("themes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("themes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

var personnePhysiqueTypePublicationStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DRAFT","PENDING","PUBLISHED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		personnePhysiqueTypePublicationStatusPropEnum = append(personnePhysiqueTypePublicationStatusPropEnum, v)
	}
}

const (

	// PersonnePhysiquePublicationStatusDRAFT captures enum value "DRAFT"
	PersonnePhysiquePublicationStatusDRAFT string = "DRAFT"

	// PersonnePhysiquePublicationStatusPENDING captures enum value "PENDING"
	PersonnePhysiquePublicationStatusPENDING string = "PENDING"

	// PersonnePhysiquePublicationStatusPUBLISHED captures enum value "PUBLISHED"
	PersonnePhysiquePublicationStatusPUBLISHED string = "PUBLISHED"
)

// prop value enum
func (m *PersonnePhysique) validatePublicationStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, personnePhysiqueTypePublicationStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PersonnePhysique) validatePublicationStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicationStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validatePublicationStatusEnum("publication_status", "body", m.PublicationStatus); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this personne physique based on the context it is used
func (m *PersonnePhysique) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHistoricalPeriod(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAuthors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepartment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRegion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCountry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTravels(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProfessions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMedias(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCenturies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateThemes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonnePhysique) contextValidateHistoricalPeriod(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.HistoricalPeriod); i++ {

		if m.HistoricalPeriod[i] != nil {

			if swag.IsZero(m.HistoricalPeriod[i]) { // not required
				return nil
			}

			if err := m.HistoricalPeriod[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("historical_period" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("historical_period" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) contextValidateAuthors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Authors); i++ {

		if m.Authors[i] != nil {

			if swag.IsZero(m.Authors[i]) { // not required
				return nil
			}

			if err := m.Authors[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("authors" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("authors" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) contextValidateCity(ctx context.Context, formats strfmt.Registry) error {

	if m.City != nil {

		if swag.IsZero(m.City) { // not required
			return nil
		}

		if err := m.City.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("city")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("city")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) contextValidateDepartment(ctx context.Context, formats strfmt.Registry) error {

	if m.Department != nil {

		if swag.IsZero(m.Department) { // not required
			return nil
		}

		if err := m.Department.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("department")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("department")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) contextValidateRegion(ctx context.Context, formats strfmt.Registry) error {

	if m.Region != nil {

		if swag.IsZero(m.Region) { // not required
			return nil
		}

		if err := m.Region.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("region")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("region")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) contextValidateCountry(ctx context.Context, formats strfmt.Registry) error {

	if m.Country != nil {

		if swag.IsZero(m.Country) { // not required
			return nil
		}

		if err := m.Country.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("country")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("country")
			}

			return err
		}
	}

	return nil
}

func (m *PersonnePhysique) contextValidateTravels(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Travels); i++ {

		if m.Travels[i] != nil {

			if swag.IsZero(m.Travels[i]) { // not required
				return nil
			}

			if err := m.Travels[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("travels" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("travels" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) contextValidateProfessions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Professions); i++ {

		if m.Professions[i] != nil {

			if swag.IsZero(m.Professions[i]) { // not required
				return nil
			}

			if err := m.Professions[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("professions" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("professions" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) contextValidateMedias(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Medias); i++ {

		if m.Medias[i] != nil {

			if swag.IsZero(m.Medias[i]) { // not required
				return nil
			}

			if err := m.Medias[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) contextValidateCenturies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Centuries); i++ {

		if m.Centuries[i] != nil {

			if swag.IsZero(m.Centuries[i]) { // not required
				return nil
			}

			if err := m.Centuries[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("centuries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("centuries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonnePhysique) contextValidateThemes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Themes); i++ {

		if m.Themes[i] != nil {

			if swag.IsZero(m.Themes[i]) { // not required
				return nil
			}

			if err := m.Themes[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("themes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("themes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PersonnePhysique) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonnePhysique) UnmarshalBinary(b []byte) error {
	var res PersonnePhysique
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
