// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAdminContributionsItem get admin contributions item
//
// swagger:model GetAdminContributionsItem
type GetAdminContributionsItem struct {

	// date
	// Required: true
	// Format: date-time
	Date *strfmt.DateTime `json:"date"`

	// event
	// Required: true
	Event *string `json:"event"`

	// category
	// Required: true
	// Enum: ["monuments_lieux","mobiliers_images","personnes_morales","personnes_physiques"]
	Category *string `json:"category"`

	// document id
	DocumentID int32 `json:"document_id,omitempty"`

	// user id
	// Format: uuid
	UserID strfmt.UUID `json:"user_id,omitempty"`

	// user firstname
	UserFirstname string `json:"user_firstname,omitempty"`

	// user lastname
	UserLastname string `json:"user_lastname,omitempty"`

	// user mail
	// Format: email
	UserMail strfmt.Email `json:"user_mail,omitempty"`

	// admin id
	// Format: uuid
	AdminID strfmt.UUID `json:"admin_id,omitempty"`

	// admin firstname
	AdminFirstname string `json:"admin_firstname,omitempty"`

	// admin lastname
	AdminLastname string `json:"admin_lastname,omitempty"`

	// admin mail
	// Format: email
	AdminMail strfmt.Email `json:"admin_mail,omitempty"`
}

// Validate validates this get admin contributions item
func (m *GetAdminContributionsItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEvent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserMail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAdminID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAdminMail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAdminContributionsItem) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("date", "body", m.Date); err != nil {
		return err
	}

	if err := validate.FormatOf("date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminContributionsItem) validateEvent(formats strfmt.Registry) error {

	if err := validate.Required("event", "body", m.Event); err != nil {
		return err
	}

	return nil
}

var getAdminContributionsItemTypeCategoryPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["monuments_lieux","mobiliers_images","personnes_morales","personnes_physiques"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAdminContributionsItemTypeCategoryPropEnum = append(getAdminContributionsItemTypeCategoryPropEnum, v)
	}
}

const (

	// GetAdminContributionsItemCategoryMonumentsLieux captures enum value "monuments_lieux"
	GetAdminContributionsItemCategoryMonumentsLieux string = "monuments_lieux"

	// GetAdminContributionsItemCategoryMobiliersImages captures enum value "mobiliers_images"
	GetAdminContributionsItemCategoryMobiliersImages string = "mobiliers_images"

	// GetAdminContributionsItemCategoryPersonnesMorales captures enum value "personnes_morales"
	GetAdminContributionsItemCategoryPersonnesMorales string = "personnes_morales"

	// GetAdminContributionsItemCategoryPersonnesPhysiques captures enum value "personnes_physiques"
	GetAdminContributionsItemCategoryPersonnesPhysiques string = "personnes_physiques"
)

// prop value enum
func (m *GetAdminContributionsItem) validateCategoryEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAdminContributionsItemTypeCategoryPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetAdminContributionsItem) validateCategory(formats strfmt.Registry) error {

	if err := validate.Required("category", "body", m.Category); err != nil {
		return err
	}

	// value enum
	if err := m.validateCategoryEnum("category", "body", *m.Category); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminContributionsItem) validateUserID(formats strfmt.Registry) error {
	if swag.IsZero(m.UserID) { // not required
		return nil
	}

	if err := validate.FormatOf("user_id", "body", "uuid", m.UserID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminContributionsItem) validateUserMail(formats strfmt.Registry) error {
	if swag.IsZero(m.UserMail) { // not required
		return nil
	}

	if err := validate.FormatOf("user_mail", "body", "email", m.UserMail.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminContributionsItem) validateAdminID(formats strfmt.Registry) error {
	if swag.IsZero(m.AdminID) { // not required
		return nil
	}

	if err := validate.FormatOf("admin_id", "body", "uuid", m.AdminID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetAdminContributionsItem) validateAdminMail(formats strfmt.Registry) error {
	if swag.IsZero(m.AdminMail) { // not required
		return nil
	}

	if err := validate.FormatOf("admin_mail", "body", "email", m.AdminMail.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get admin contributions item based on context it is used
func (m *GetAdminContributionsItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAdminContributionsItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAdminContributionsItem) UnmarshalBinary(b []byte) error {
	var res GetAdminContributionsItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
