// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PersonneMorale personne morale
//
// swagger:model PersonneMorale
type PersonneMorale struct {

	// ID of the legal entity
	ID int32 `json:"id,omitempty"`

	// Title of the legal entity
	Title string `json:"title,omitempty"`

	// Has foundation deed
	FoundationDeed bool `json:"foundation_deed,omitempty"`

	// History of the legal entity
	History string `json:"history,omitempty"`

	// bibliography of the legal entity
	Bibliography string `json:"bibliography,omitempty"`

	// Is simple mention
	SimpleMention bool `json:"simple_mention,omitempty"`

	// status text
	StatusText bool `json:"status_text,omitempty"`

	// How it worked
	Process string `json:"process,omitempty"`

	// How it impacted the social life
	SocialInvolvement string `json:"social_involvement,omitempty"`

	// Linked objects
	Objects string `json:"objects,omitempty"`

	// assets
	Biens string `json:"biens,omitempty"`

	// first mention date
	DatePremiereMention string `json:"date_premiere_mention,omitempty"`

	// last mention date
	DateDerniereMention string `json:"date_derniere_mention,omitempty"`

	// refoundation date
	RefondationDate string `json:"refondation_date,omitempty"`

	// end date
	DateFin string `json:"date_fin,omitempty"`

	// social/professional origin
	OrigineSocialeProf string `json:"origine_sociale_prof,omitempty"`

	// known members
	MembresConnus string `json:"membres_connus,omitempty"`

	// meeting frequency
	FrequenceReunions string `json:"frequence_reunions,omitempty"`

	// political involvement
	ParticipationViePol string `json:"participation_vie_pol,omitempty"`

	// funerals
	Funerailles string `json:"funerailles,omitempty"`

	// other celebrations
	AutresFetes string `json:"autres_fetes,omitempty"`

	// burial/costume
	InhumationCostume string `json:"inhumation_costume,omitempty"`

	// founders
	Fondateurs string `json:"fondateurs,omitempty"`

	// statutes
	Statuts string `json:"statuts,omitempty"`

	// authorizations
	Autorisations string `json:"autorisations,omitempty"`

	// sources of the legal entity
	Sources string `json:"sources,omitempty"`

	// creation date of the entry (null when the record has no creation nor update date)
	// Format: date
	CreationDate *strfmt.Date `json:"creation_date,omitempty"`

	// update date of the entry (null when the record has no update date)
	// Format: date
	UpdateDate *strfmt.Date `json:"update_date,omitempty"`

	// is entry published
	Published bool `json:"published,omitempty"`

	// name of the contributors
	Contributors string `json:"contributors,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// entry authors
	Authors []*BasicFilter `json:"authors"`

	// city of the legal entity
	City *BasicFilter `json:"city,omitempty"`

	// department of the legal entity
	Department *BasicFilter `json:"department,omitempty"`

	// region of the legal entity
	Region *BasicFilter `json:"region,omitempty"`

	// country of the legal entity
	Country *BasicFilter `json:"country,omitempty"`

	// natures of the monument lieu
	Natures []*BasicFilter `json:"natures"`

	// images ID of the monument lieu
	Medias []*Media `json:"medias"`

	// time period of the monument lieu
	Centuries []*BasicFilter `json:"centuries"`

	// linked monuments places
	LinkedMonumentsPlaces []int32 `json:"linked_monuments_places"`

	// linked individuals
	LinkedIndividuals []int32 `json:"linked_individuals"`

	// linked furniture images
	LinkedFurnitureImages []int32 `json:"linked_furniture_images"`

	// linked legal entities
	LinkedLegalEntities []int32 `json:"linked_legal_entities"`

	// themes
	Themes []*BasicFilter `json:"themes"`

	// parent id
	ParentID int32 `json:"parent_id,omitempty"`

	// publication status of the entry
	// Enum: ["DRAFT","PENDING","PUBLISHED"]
	PublicationStatus string `json:"publication_status,omitempty"`

	// comment of the temoin
	TemoinComment string `json:"temoinComment,omitempty"`
}

// Validate validates this personne morale
func (m *PersonneMorale) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDepartment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedias(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCenturies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThemes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicationStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonneMorale) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_date", "body", "date", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PersonneMorale) validateUpdateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("update_date", "body", "date", m.UpdateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PersonneMorale) validateAuthors(formats strfmt.Registry) error {
	if swag.IsZero(m.Authors) { // not required
		return nil
	}

	for i := 0; i < len(m.Authors); i++ {
		if swag.IsZero(m.Authors[i]) { // not required
			continue
		}

		if m.Authors[i] != nil {
			if err := m.Authors[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("authors" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("authors" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) validateCity(formats strfmt.Registry) error {
	if swag.IsZero(m.City) { // not required
		return nil
	}

	if m.City != nil {
		if err := m.City.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("city")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("city")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) validateDepartment(formats strfmt.Registry) error {
	if swag.IsZero(m.Department) { // not required
		return nil
	}

	if m.Department != nil {
		if err := m.Department.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("department")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("department")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) validateRegion(formats strfmt.Registry) error {
	if swag.IsZero(m.Region) { // not required
		return nil
	}

	if m.Region != nil {
		if err := m.Region.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("region")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("region")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) validateCountry(formats strfmt.Registry) error {
	if swag.IsZero(m.Country) { // not required
		return nil
	}

	if m.Country != nil {
		if err := m.Country.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("country")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("country")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) validateNatures(formats strfmt.Registry) error {
	if swag.IsZero(m.Natures) { // not required
		return nil
	}

	for i := 0; i < len(m.Natures); i++ {
		if swag.IsZero(m.Natures[i]) { // not required
			continue
		}

		if m.Natures[i] != nil {
			if err := m.Natures[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("natures" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("natures" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) validateMedias(formats strfmt.Registry) error {
	if swag.IsZero(m.Medias) { // not required
		return nil
	}

	for i := 0; i < len(m.Medias); i++ {
		if swag.IsZero(m.Medias[i]) { // not required
			continue
		}

		if m.Medias[i] != nil {
			if err := m.Medias[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) validateCenturies(formats strfmt.Registry) error {
	if swag.IsZero(m.Centuries) { // not required
		return nil
	}

	for i := 0; i < len(m.Centuries); i++ {
		if swag.IsZero(m.Centuries[i]) { // not required
			continue
		}

		if m.Centuries[i] != nil {
			if err := m.Centuries[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("centuries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("centuries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) validateThemes(formats strfmt.Registry) error {
	if swag.IsZero(m.Themes) { // not required
		return nil
	}

	for i := 0; i < len(m.Themes); i++ {
		if swag.IsZero(m.Themes[i]) { // not required
			continue
		}

		if m.Themes[i] != nil {
			if err := m.Themes[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("themes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("themes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

var personneMoraleTypePublicationStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DRAFT","PENDING","PUBLISHED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		personneMoraleTypePublicationStatusPropEnum = append(personneMoraleTypePublicationStatusPropEnum, v)
	}
}

const (

	// PersonneMoralePublicationStatusDRAFT captures enum value "DRAFT"
	PersonneMoralePublicationStatusDRAFT string = "DRAFT"

	// PersonneMoralePublicationStatusPENDING captures enum value "PENDING"
	PersonneMoralePublicationStatusPENDING string = "PENDING"

	// PersonneMoralePublicationStatusPUBLISHED captures enum value "PUBLISHED"
	PersonneMoralePublicationStatusPUBLISHED string = "PUBLISHED"
)

// prop value enum
func (m *PersonneMorale) validatePublicationStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, personneMoraleTypePublicationStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PersonneMorale) validatePublicationStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicationStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validatePublicationStatusEnum("publication_status", "body", m.PublicationStatus); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this personne morale based on the context it is used
func (m *PersonneMorale) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDepartment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRegion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCountry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNatures(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMedias(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCenturies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateThemes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonneMorale) contextValidateAuthors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Authors); i++ {

		if m.Authors[i] != nil {

			if swag.IsZero(m.Authors[i]) { // not required
				return nil
			}

			if err := m.Authors[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("authors" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("authors" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) contextValidateCity(ctx context.Context, formats strfmt.Registry) error {

	if m.City != nil {

		if swag.IsZero(m.City) { // not required
			return nil
		}

		if err := m.City.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("city")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("city")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) contextValidateDepartment(ctx context.Context, formats strfmt.Registry) error {

	if m.Department != nil {

		if swag.IsZero(m.Department) { // not required
			return nil
		}

		if err := m.Department.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("department")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("department")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) contextValidateRegion(ctx context.Context, formats strfmt.Registry) error {

	if m.Region != nil {

		if swag.IsZero(m.Region) { // not required
			return nil
		}

		if err := m.Region.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("region")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("region")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) contextValidateCountry(ctx context.Context, formats strfmt.Registry) error {

	if m.Country != nil {

		if swag.IsZero(m.Country) { // not required
			return nil
		}

		if err := m.Country.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("country")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("country")
			}

			return err
		}
	}

	return nil
}

func (m *PersonneMorale) contextValidateNatures(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Natures); i++ {

		if m.Natures[i] != nil {

			if swag.IsZero(m.Natures[i]) { // not required
				return nil
			}

			if err := m.Natures[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("natures" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("natures" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) contextValidateMedias(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Medias); i++ {

		if m.Medias[i] != nil {

			if swag.IsZero(m.Medias[i]) { // not required
				return nil
			}

			if err := m.Medias[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("medias" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("medias" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) contextValidateCenturies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Centuries); i++ {

		if m.Centuries[i] != nil {

			if swag.IsZero(m.Centuries[i]) { // not required
				return nil
			}

			if err := m.Centuries[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("centuries" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("centuries" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PersonneMorale) contextValidateThemes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Themes); i++ {

		if m.Themes[i] != nil {

			if swag.IsZero(m.Themes[i]) { // not required
				return nil
			}

			if err := m.Themes[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("themes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("themes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PersonneMorale) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonneMorale) UnmarshalBinary(b []byte) error {
	var res PersonneMorale
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
