// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetUserHistoryItem get user history item
//
// swagger:model GetUserHistoryItem
type GetUserHistoryItem struct {

	// date
	// Required: true
	// Format: date-time
	Date *strfmt.DateTime `json:"date"`

	// event
	// Required: true
	Event *string `json:"event"`

	// category
	// Required: true
	// Enum: ["monuments_lieux","mobiliers_images","personnes_morales","personnes_physiques"]
	Category *string `json:"category"`

	// document id
	DocumentID int32 `json:"document_id,omitempty"`
}

// Validate validates this get user history item
func (m *GetUserHistoryItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEvent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCategory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetUserHistoryItem) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("date", "body", m.Date); err != nil {
		return err
	}

	if err := validate.FormatOf("date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetUserHistoryItem) validateEvent(formats strfmt.Registry) error {

	if err := validate.Required("event", "body", m.Event); err != nil {
		return err
	}

	return nil
}

var getUserHistoryItemTypeCategoryPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["monuments_lieux","mobiliers_images","personnes_morales","personnes_physiques"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getUserHistoryItemTypeCategoryPropEnum = append(getUserHistoryItemTypeCategoryPropEnum, v)
	}
}

const (

	// GetUserHistoryItemCategoryMonumentsLieux captures enum value "monuments_lieux"
	GetUserHistoryItemCategoryMonumentsLieux string = "monuments_lieux"

	// GetUserHistoryItemCategoryMobiliersImages captures enum value "mobiliers_images"
	GetUserHistoryItemCategoryMobiliersImages string = "mobiliers_images"

	// GetUserHistoryItemCategoryPersonnesMorales captures enum value "personnes_morales"
	GetUserHistoryItemCategoryPersonnesMorales string = "personnes_morales"

	// GetUserHistoryItemCategoryPersonnesPhysiques captures enum value "personnes_physiques"
	GetUserHistoryItemCategoryPersonnesPhysiques string = "personnes_physiques"
)

// prop value enum
func (m *GetUserHistoryItem) validateCategoryEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getUserHistoryItemTypeCategoryPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetUserHistoryItem) validateCategory(formats strfmt.Registry) error {

	if err := validate.Required("category", "body", m.Category); err != nil {
		return err
	}

	// value enum
	if err := m.validateCategoryEnum("category", "body", *m.Category); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get user history item based on context it is used
func (m *GetUserHistoryItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetUserHistoryItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetUserHistoryItem) UnmarshalBinary(b []byte) error {
	var res GetUserHistoryItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
