// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MonumentsLieuxListFilters monuments lieux list filters
//
// swagger:model MonumentsLieuxListFilters
type MonumentsLieuxListFilters struct {

	// countries
	Countries []int32 `json:"countries"`

	// regions
	Regions []int32 `json:"regions"`

	// departments
	Departments []int32 `json:"departments"`

	// cities
	Cities []int32 `json:"cities"`

	// centuries
	Centuries []int32 `json:"centuries"`

	// natures
	Natures []int32 `json:"natures"`

	// states
	States []int32 `json:"states"`

	// creators
	Creators []int32 `json:"creators"`

	// authors
	Authors []int32 `json:"authors"`

	// materials
	Materials []int32 `json:"materials"`

	// legal entities
	LegalEntities []int32 `json:"legal_entities"`

	// individuals
	Individuals []int32 `json:"individuals"`

	// furniture
	Furniture []int32 `json:"furniture"`
}

// Validate validates this monuments lieux list filters
func (m *MonumentsLieuxListFilters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this monuments lieux list filters based on context it is used
func (m *MonumentsLieuxListFilters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MonumentsLieuxListFilters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MonumentsLieuxListFilters) UnmarshalBinary(b []byte) error {
	var res MonumentsLieuxListFilters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
