// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auteurs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuteur = `-- name: CreateAuteur :one
INSERT INTO bib_auteurs (auteur_fiche_nom, user_id)
VALUES ($1, $2)
RETURNING id_auteur_fiche
`

type CreateAuteurParams struct {
	Name   pgtype.Text
	UserID pgtype.Text
}

func (q *Queries) CreateAuteur(ctx context.Context, arg CreateAuteurParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAuteur, arg.Name, arg.UserID)
	var id_auteur_fiche int32
	err := row.Scan(&id_auteur_fiche)
	return id_auteur_fiche, err
}

const getAuteurByName = `-- name: GetAuteurByName :one
SELECT id_auteur_fiche, auteur_fiche_nom, user_id
FROM bib_auteurs
WHERE auteur_fiche_nom = $1
`

func (q *Queries) GetAuteurByName(ctx context.Context, auteurFicheNom pgtype.Text) (BibAuteur, error) {
	row := q.db.QueryRow(ctx, getAuteurByName, auteurFicheNom)
	var i BibAuteur
	err := row.Scan(&i.IDAuteurFiche, &i.AuteurFicheNom, &i.UserID)
	return i, err
}

const getAuteurByUserID = `-- name: GetAuteurByUserID :one
SELECT id_auteur_fiche, auteur_fiche_nom, user_id
FROM bib_auteurs
WHERE user_id = $1
`

func (q *Queries) GetAuteurByUserID(ctx context.Context, userID pgtype.Text) (BibAuteur, error) {
	row := q.db.QueryRow(ctx, getAuteurByUserID, userID)
	var i BibAuteur
	err := row.Scan(&i.IDAuteurFiche, &i.AuteurFicheNom, &i.UserID)
	return i, err
}

const getAuteurIDByMobImg = `-- name: GetAuteurIDByMobImg :one
SELECT auteur_fiche_mob_img_id
FROM cor_auteur_fiche_mob_img
WHERE mobilier_image_id = $1
`

func (q *Queries) GetAuteurIDByMobImg(ctx context.Context, mobilierImageID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAuteurIDByMobImg, mobilierImageID)
	var auteur_fiche_mob_img_id int32
	err := row.Scan(&auteur_fiche_mob_img_id)
	return auteur_fiche_mob_img_id, err
}

const getAuteurIDByMonuLieu = `-- name: GetAuteurIDByMonuLieu :one
SELECT auteur_fiche_monu_lieu_id
FROM cor_auteur_fiche_monu_lieu
WHERE monument_lieu_id = $1
`

func (q *Queries) GetAuteurIDByMonuLieu(ctx context.Context, monumentLieuID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAuteurIDByMonuLieu, monumentLieuID)
	var auteur_fiche_monu_lieu_id int32
	err := row.Scan(&auteur_fiche_monu_lieu_id)
	return auteur_fiche_monu_lieu_id, err
}

const getAuteurIDByPersMoID = `-- name: GetAuteurIDByPersMoID :one
SELECT auteur_fiche_pers_mo_id
FROM cor_auteur_fiche_pers_mo
WHERE pers_morale_id = $1
`

func (q *Queries) GetAuteurIDByPersMoID(ctx context.Context, persMoraleID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAuteurIDByPersMoID, persMoraleID)
	var auteur_fiche_pers_mo_id int32
	err := row.Scan(&auteur_fiche_pers_mo_id)
	return auteur_fiche_pers_mo_id, err
}

const getAuteurIDByPersPhyID = `-- name: GetAuteurIDByPersPhyID :one
SELECT auteur_fiche_pers_phy_id
FROM cor_auteur_fiche_pers_phy
WHERE pers_physique_id = $1
`

func (q *Queries) GetAuteurIDByPersPhyID(ctx context.Context, persPhysiqueID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAuteurIDByPersPhyID, persPhysiqueID)
	var auteur_fiche_pers_phy_id int32
	err := row.Scan(&auteur_fiche_pers_phy_id)
	return auteur_fiche_pers_phy_id, err
}
