// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auteurs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuteur = `-- name: CreateAuteur :one
INSERT INTO bib_auteurs (auteur_fiche_nom)
VALUES ($1)
RETURNING id_auteur_fiche
`

func (q *Queries) CreateAuteur(ctx context.Context, name pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, createAuteur, name)
	var id_auteur_fiche int32
	err := row.Scan(&id_auteur_fiche)
	return id_auteur_fiche, err
}

const getAuteurByName = `-- name: GetAuteurByName :one
SELECT id_auteur_fiche, auteur_fiche_nom
FROM bib_auteurs
WHERE auteur_fiche_nom = $1
`

func (q *Queries) GetAuteurByName(ctx context.Context, auteurFicheNom pgtype.Text) (BibAuteur, error) {
	row := q.db.QueryRow(ctx, getAuteurByName, auteurFicheNom)
	var i BibAuteur
	err := row.Scan(&i.IDAuteurFiche, &i.AuteurFicheNom)
	return i, err
}
