swagger: "2.0"
info:
  version: "1.0.0"
  title: "Common"
tags:
  - name: "supervision"
    description: "Probes"
schemes:
  - "http"

paths:
  /health:
    get:
      tags:
        - "supervision"
      summary: "Get readiness status"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Service"
        "500":
          description: "KO"
          schema:
            $ref: "#/definitions/Service"
  /status:
    get:
      tags:
        - "supervision"
      summary: "Get liveness status"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Service"
definitions:
  Service:
    type: "object"
    properties:
      name:
        type: "string"
      status:
        type: "string"
        enum:
          - "OK"
          - "KO"
      details:
        type: "string"
      services:
        type: "array"
        x-omitempty: true
        items:
          $ref: "#/definitions/ServiceItem"
  ServiceItem:
    type: "object"
    properties:
      name:
        type: "string"
      status:
        type: "string"
        enum:
          - "OK"
          - "KO"
      details:
        type: "string"