name: Manage Go code (linters, checks, tests)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:24-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

      - name: Install deps
        run: ./bin/task deps

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...      

      - name: Run linters
        run: ./bin/task ci-lint

      - name: Run integration tests
        run: ./bin/task cover